Introduced `typos` pre-commit hook. _typos.toml is used to discard false positives in email headers:
error: `Forr` should be `For`
--> tests/data/spec_no_trailing_newline/patch0.patch:2:26
|
2 | From: =?UTF-8?q?Nikola=20Forr=C3=B3?= <nforro@redhat.com>
|                          ^^^^